config/routes.rb
Rails.application.routes.draw do
  root "shopper#index", as: 'root'

  # post 'access/new', to:'access#new'
  # post 'access', to:'access#new'

  post 'access/new', to:'access#create'

  get 'access/new', to:'access#new'

  get 'login', to: 'access#new'

  get 'access/create'
  get 'authenticate', to: 'access#create'

  get 'access/destroy'
  get 'logout', to: 'access#destroy'

  delete 'logout', to: 'access#destroy'

  get 'admin/index'
  get 'admin', to: 'admin#index'

  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'shopper/index'
  get 'shopper', to: 'shopper#index'


  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Store</title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div id="banner">
		<%= image_tag("logo.png", :size => "100x50") %>
		<%= @page_title || "Our Products" %>
	</div>
	<div id="columns">
		<div id="side">

			<div id="cart">
				<% if @cart %>
				<%= render @cart %>
				<% end %>
			</div>

			<ul>
				<li><%= link_to 'Home', root_path %></li>
				<li><%#= link_to 'About', about_path %></li>
				<li><a href="http://www..../contact">Contact</a></li>
				<li><%= link_to 'Admin', access_new_path %></li>
			</ul>

			<% if session[:user_id] %>
			<ul>
				<li><%= link_to 'Orders', orders_path %></li>
				<li><%= link_to 'Products', products_path %></li>
				<li><%= link_to 'Users', users_path %></li>
			</ul>
			<%= button_to 'Logout', logout_path, method: :delete %>
			<% end %>
			
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>